apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://runatlantis.github.io/helm-charts
      chart: atlantis
      targetRevision: 5.1.0
      helm:
        valueFiles:
          - $values/atlantis-values/values.yaml
    - repoURL: https://github.com/chaitanyakanakaminfra-lab/eks-cost-demo
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: atlantis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
