apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 85.3.3
    helm:
     values: |
        grafana:
          adminPassword: "demo-grafana-2024"
          service:
            type: ClusterIP
          persistence:
            enabled: false
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 256Mi
        prometheus:
          prometheusSpec:
            retention: 24h
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
        alertmanager:
          alertmanagerSpec:
            resources:
              requests:
                cpu: 25m
                memory: 64Mi
        nodeExporter:
          enabled: true
        kubeStateMetrics:
          enabled: true
