apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: search-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/chaitanyakanakaminfra-lab/eks-cost-demo
    targetRevision: HEAD
    path: helm-charts/search-api
  destination:
    server: https://kubernetes.default.svc
    namespace: search
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
